services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3310:3306"
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: ./backend
    container_name: flask-api
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
